language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
  - cd dist && echo 'practice.0x06.cn' > CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN 
  keep_history: true
  target_branch: master
  repo: m9-lab/m9-lab.github.io
  name: $GIT_NAME
  email: $GIT_EMAIL
  on:
    branch: master
